export type MissionRecord = Record<string, unknown>;
export type MissionStage = "WAITING" | "HARVESTING" | "DRYING" | "FINISHED" | "TO_REVIEW" | "COMPLETED";
export type MissionStatus = "ACTIVE" | "CLOSEOUT" | "COMPLETED";
export type MissionStepStatus = "SCHEDULED" | "IN_PROGRESS" | "COMPLETED";
export type MissionCloseoutInput = { actualHarvestKg: number; actualDriedKg: number; harvestedAreaHectares: number | null; buyerTargetMet: boolean; dryingCompleted: boolean; rejectedKg: number | null; notes: string | null };
export type MessageInput = { role: "farmer" | "assistant"; content: string };
export type FactProvenance = "FARMER_REPORTED" | "INFERRED";
export type FactConfidence = "high" | "medium" | "low";
export type MissionFactKey = "fieldBlockId" | "cropBatchIds" | "buyerCommitmentId" | "buyerQuantityKg" | "marketQuality" | "plannedHarvestKg" | "plannedDriedKg" | "deadline" | "availableWorkerCount" | "coveredDryingCapacityKg" | "notes";
export type MissionFactReview = { key: MissionFactKey; status: "confirmed" | "needs_clarification" | "missing"; reason: string; provenance: FactProvenance; confidence: FactConfidence };
export type MissionFact = {
  fieldBlockId: string | null;
  cropBatchIds: string[];
  buyerCommitmentId: string | null;
  buyerQuantityKg: number | null;
  marketQuality: "Grade A" | "Grade B" | "Grade C" | null;
  plannedHarvestKg: number | null;
  plannedDriedKg: number | null;
  deadline: string | null;
  availableWorkerCount: number | null;
  coveredDryingCapacityKg: number | null;
  notes: string | null;
  clarification: { key: string; question: string } | null;
};
export type FactBlock = { key: string; value: unknown; provenance: FactProvenance; confidence: FactConfidence };
export type MissionInterpretation = { facts: MissionFact; review: MissionFactReview[] };
export type MissionManualOptions = { timezone: string; fieldBlocks: Array<{ fieldBlockId: string; name: string }>; cropBatches: Array<{ cropBatchId: string; fieldBlockId: string; label: string }> };
export type MissionCandidate = { previewId: string; messages: MessageInput[]; facts: MissionFact; review: MissionFactReview[]; blocks: FactBlock[]; manualOptions?: MissionManualOptions };
export type PlannedActivity = {
  title: string;
  description: string;
  scheduleType: "DAILY_WINDOW" | "DATE_RANGE";
  startsOn: string;
  endsOn: string;
  windowStart: string | null;
  windowEnd: string | null;
  timezone: string;
  isConditional: boolean;
  stage: "HARVESTING" | "DRYING";
  targetHarvestKg?: number | null;
};
export type GeneratedPlan = { planId?: string; name: string; summary: string; recommended: boolean; assumptions: string[]; risks: Record<string, string>; dryingEstimateDays: number; dryingEstimateReason: string; activities: PlannedActivity[] };
export type CloseoutSummary = { summary: string; lessons: string[] };
